<a href="https://colab.research.google.com/github/pratheeshsailor/INF-Data-EDA-/blob/main/Brew_INF_Audits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from urllib.parse import urlparse

file_path = "/content/US.xlsx"              #  change file name
df = pd.read_excel(file_path)

In [ ]:
pivot_table = pd.pivot_table(
    df[df["criteria_name"].str.startswith("amzn1", na=False)],
    index="mapper_id",
    columns="mapping_status",
    values="sku",
    aggfunc="count",
    # margins=True,
    fill_value=0
)
pivot_table

mapping_status                    IF  INF  PIF  PINF  RIF  UNKNOWN
mapper_id
LLM_MISMATCH_azbmoham@amazon.com   4    0    0     0    0        0
LLM_MISMATCH_nkalyans@amazon.com   1    0    0     0    0        0
LLM_MISMATCH_rashriy@amazon.com    2    0    0     0    0        0
LLM_MISMATCH_smprashu@amazon.com   1    0    0     0    0        0
ablessil@amazon.com                3   47    0     0    0       15
afm_brew_automation                0    0    0    11    0      245
akansagg@amazon.com               17  486   11     0    0       26
akelneeh@amazon.com                9  501    0     0    3      281
akojsiri@amazon.com                3  313    0     0    0      148
anupriyo@amazon.com                4  233    0     0    1       60
arisrasp@amazon.com                5  348    0     0    0       80
arvindsw@amazon.com               35  191   19     0    1       29
azbmoham@amazon.com               28  404    0     0    3       60
bihanifa@amazon.com                0  846    0     0    0       12
bolleraj@amazon.com               10  233    0     0    0      110
budhayas@amazon.com                0  189    0     0    0       51
chouanam@amazon.com               19  435    0     0    0       97
insachin@amazon.com                6  418    0     0    0       52
jawmdsaq@amazon.com               13  444    0     0    0       48
jidmat@amazon.com                  4  600    1     0    0       87
jrahsehg@amazon.com                0  589    0     0    0       24
krrishch@amazon.com                5  112    0     0    0        8
kshlkr@amazon.com                 84  618    0     0    0      124
lpavkuma@amazon.com               44  212    0     0    1        9
magukris@amazon.com                9  394    0     0    1       53
mkupasna@amazon.com               54  921    0     0    1       26
mmt_brahma@amazon.com              0    0    0     0    0     1676
mohandvi@amazon.com                9  160    0     0    0       15
nehakj@amazon.com                  0   24    0     0    0       43
nkalyans@amazon.com               99  601    0     0    2       36
prajunan@amazon.com                1  418    0     0    0       19
preethko@amazon.com               92  509    1     0    1       51
rashriy@amazon.com                42  555    0     0    1       15
renusasa@amazon.com                5  116    0     0    0       45
saidsk@amazon.com                 18  627    0     0    4      144
sanechak@amazon.com                3  532    0     0    0       15
satytumm@amazon.com               95  616    0     0    2       82
smprashu@amazon.com               16  317    0     0    1       65
summaybe@amazon.com                2  186    0     0    0        6
vaasuki@amazon.com                 1  328    0     0    0       45
vramesho@amazon.com               20  301    0     0    2      113
vsandemo@amazon.com               22  280    0     0    0       20

In [ ]:
pivot_table = pivot_table.rename(
    index={"All": "Total"},
    columns={"All": "Total"}
)

In [ ]:
# Add IF + INF total column
pivot_table["IF_INF_Total"] = pivot_table.get("IF", 0) + pivot_table.get("INF", 0)

pivot_table

mapping_status,IF,INF,PIF,PINF,RIF,UNKNOWN,IF_INF_Total
mapper_id,,,,,,,
LLM_MISMATCH_azbmoham@amazon.com,4,0,0,0,0,0,4
LLM_MISMATCH_nkalyans@amazon.com,1,0,0,0,0,0,1
LLM_MISMATCH_rashriy@amazon.com,2,0,0,0,0,0,2
LLM_MISMATCH_smprashu@amazon.com,1,0,0,0,0,0,1
ablessil@amazon.com,3,47,0,0,0,15,50
afm_brew_automation,0,0,0,11,0,245,0
akansagg@amazon.com,17,486,11,0,0,26,503
akelneeh@amazon.com,9,501,0,0,3,281,510
akojsiri@amazon.com,3,313,0,0,0,148,316
anupriyo@amazon.com,4,233,0,0,1,60,237
arisrasp@amazon.com,5,348,0,0,0,80,353
arvindsw@amazon.com,35,191,19,0,1,29,226
azbmoham@amazon.com,28,404,0,0,3,60,432
bihanifa@amazon.com,0,846,0,0,0,12,846
bolleraj@amazon.com,10,233,0,0,0,110,243
budhayas@amazon.com,0,189,0,0,0,51,189
chouanam@amazon.com,19,435,0,0,0,97,454
insachin@amazon.com,6,418,0,0,0,52,424
jawmdsaq@amazon.com,13,444,0,0,0,48,457
jidmat@amazon.com,4,600,1,0,0,87,604
jrahsehg@amazon.com,0,589,0,0,0,24,589
krrishch@amazon.com,5,112,0,0,0,8,117
kshlkr@amazon.com,84,618,0,0,0,124,702
lpavkuma@amazon.com,44,212,0,0,1,9,256
magukris@amazon.com,9,394,0,0,1,53,403
mkupasna@amazon.com,54,921,0,0,1,26,975
mmt_brahma@amazon.com,0,0,0,0,0,1676,0
mohandvi@amazon.com,9,160,0,0,0,15,169
nehakj@amazon.com,0,24,0,0,0,43,24
nkalyans@amazon.com,99,601,0,0,2,36,700
prajunan@amazon.com,1,418,0,0,0,19,419
preethko@amazon.com,92,509,1,0,1,51,601
rashriy@amazon.com,42,555,0,0,1,15,597
renusasa@amazon.com,5,116,0,0,0,45,121
saidsk@amazon.com,18,627,0,0,4,144,645
sanechak@amazon.com,3,532,0,0,0,15,535
satytumm@amazon.com,95,616,0,0,2,82,711
smprashu@amazon.com,16,317,0,0,1,65,333
summaybe@amazon.com,2,186,0,0,0,6,188
vaasuki@amazon.com,1,328,0,0,0,45,329
vramesho@amazon.com,20,301,0,0,2,113,321
vsandemo@amazon.com,22,280,0,0,0,20,302

In [ ]:
pivot_table['IF_Percentage'] = (
    (pivot_table['IF'] / pivot_table['IF_INF_Total']) * 100
).round(0)
pivot_table

mapping_status,IF,INF,PIF,PINF,RIF,UNKNOWN,IF_INF_Total,IF_Percentage
mapper_id,,,,,,,,
LLM_MISMATCH_azbmoham@amazon.com,4,0,0,0,0,0,4,100.0
LLM_MISMATCH_nkalyans@amazon.com,1,0,0,0,0,0,1,100.0
LLM_MISMATCH_rashriy@amazon.com,2,0,0,0,0,0,2,100.0
LLM_MISMATCH_smprashu@amazon.com,1,0,0,0,0,0,1,100.0
ablessil@amazon.com,3,47,0,0,0,15,50,6.0
afm_brew_automation,0,0,0,11,0,245,0,NaN
akansagg@amazon.com,17,486,11,0,0,26,503,3.0
akelneeh@amazon.com,9,501,0,0,3,281,510,2.0
akojsiri@amazon.com,3,313,0,0,0,148,316,1.0
anupriyo@amazon.com,4,233,0,0,1,60,237,2.0
arisrasp@amazon.com,5,348,0,0,0,80,353,1.0
arvindsw@amazon.com,35,191,19,0,1,29,226,15.0
azbmoham@amazon.com,28,404,0,0,3,60,432,6.0
bihanifa@amazon.com,0,846,0,0,0,12,846,0.0
bolleraj@amazon.com,10,233,0,0,0,110,243,4.0
budhayas@amazon.com,0,189,0,0,0,51,189,0.0
chouanam@amazon.com,19,435,0,0,0,97,454,4.0
insachin@amazon.com,6,418,0,0,0,52,424,1.0
jawmdsaq@amazon.com,13,444,0,0,0,48,457,3.0
jidmat@amazon.com,4,600,1,0,0,87,604,1.0
jrahsehg@amazon.com,0,589,0,0,0,24,589,0.0
krrishch@amazon.com,5,112,0,0,0,8,117,4.0
kshlkr@amazon.com,84,618,0,0,0,124,702,12.0
lpavkuma@amazon.com,44,212,0,0,1,9,256,17.0
magukris@amazon.com,9,394,0,0,1,53,403,2.0
mkupasna@amazon.com,54,921,0,0,1,26,975,6.0
mmt_brahma@amazon.com,0,0,0,0,0,1676,0,NaN
mohandvi@amazon.com,9,160,0,0,0,15,169,5.0
nehakj@amazon.com,0,24,0,0,0,43,24,0.0
nkalyans@amazon.com,99,601,0,0,2,36,700,14.0
prajunan@amazon.com,1,418,0,0,0,19,419,0.0
preethko@amazon.com,92,509,1,0,1,51,601,15.0
rashriy@amazon.com,42,555,0,0,1,15,597,7.0
renusasa@amazon.com,5,116,0,0,0,45,121,4.0
saidsk@amazon.com,18,627,0,0,4,144,645,3.0
sanechak@amazon.com,3,532,0,0,0,15,535,1.0
satytumm@amazon.com,95,616,0,0,2,82,711,13.0
smprashu@amazon.com,16,317,0,0,1,65,333,5.0
summaybe@amazon.com,2,186,0,0,0,6,188,1.0
vaasuki@amazon.com,1,328,0,0,0,45,329,0.0
vramesho@amazon.com,20,301,0,0,2,113,321,6.0
vsandemo@amazon.com,22,280,0,0,0,20,302,7.0

In [ ]:
pivot_table = pivot_table.reset_index()

In [ ]:
final_df = pivot_table.copy()

# Remove @amazon.com
final_df["user"] = final_df["mapper_id"].str.replace("@amazon.com", "", regex=False)

# Empty columns (will be filled from EMP file)
final_df["Emp Name"] = ""
final_df["Manager"] = ""
final_df["Team Name"] = ""

In [ ]:
final_df = final_df.rename(columns={
    "IF_INF_Total": "Total Mappings",
    "IF": "No of IF's",
    "INF": "No of INF's",
    "IF_Percentage": "IF%"
})

In [ ]:
emp_df = pd.read_excel("/content/Emp.xlsx")

# Clean user column for safe matching
emp_df["user"] = emp_df["user"].astype(str).str.strip()
final_df["user"] = final_df["user"].astype(str).str.strip()

In [ ]:
final_df = final_df.merge(
    emp_df[["user", "Emp Name", "Manager", "Team Name"]],
    on="user",
    how="left"
)
final_df

,mapper_id,No of IF's,No of INF's,PIF,PINF,RIF,UNKNOWN,Total Mappings,IF%,user,Emp Name_x,Manager_x,Team Name_x,Emp Name_y,Manager_y,Team Name_y
0,LLM_MISMATCH_azbmoham@amazon.com,4,0,0,0,0,0,4,100.0,LLM_MISMATCH_azbmoham,,,,NaN,NaN,NaN
1,LLM_MISMATCH_nkalyans@amazon.com,1,0,0,0,0,0,1,100.0,LLM_MISMATCH_nkalyans,,,,NaN,NaN,NaN
2,LLM_MISMATCH_rashriy@amazon.com,2,0,0,0,0,0,2,100.0,LLM_MISMATCH_rashriy,,,,NaN,NaN,NaN
3,LLM_MISMATCH_smprashu@amazon.com,1,0,0,0,0,0,1,100.0,LLM_MISMATCH_smprashu,,,,NaN,NaN,NaN
4,ablessil@amazon.com,3,47,0,0,0,15,50,6.0,ablessil,,,,Blessing Alciya A,Saranya M L,US
5,afm_brew_automation,0,0,0,11,0,245,0,NaN,afm_brew_automation,,,,NaN,NaN,NaN
6,akansagg@amazon.com,17,486,11,0,0,26,503,3.0,akansagg,,,,AKANSHA AGGARWAL,Karthik S,US
7,akelneeh@amazon.com,9,501,0,0,3,281,510,2.0,akelneeh,,,,Neeharika Akella Venkata Sai,Karthik S,US
8,akojsiri@amazon.com,3,313,0,0,0,148,316,1.0,akojsiri,,,,Shirisha Akoju,Arun Sarathy S,US
9,anupriyo@amazon.com,4,233,0,0,1,60,237,2.0,anupriyo,,,,NaN,NaN,NaN
10,arisrasp@amazon.com,5,348,0,0,0,80,353,1.0,arisrasp,,,,Arisa Rashid,Abhishek Prabhakar,US
11,arvindsw@amazon.com,35,191,19,0,1,29,226,15.0,arvindsw,,,,Arvindswamy Chandrasekaran,Gokul Balaiyan,US
12,azbmoham@amazon.com,28,404,0,0,3,60,432,6.0,azbmoham,,,,Mohammed Azarudeen,Saranya M L,US
13,bihanifa@amazon.com,0,846,0,0,0,12,846,0.0,bihanifa,,,,Hanifa,Arun Joseph,US
14,bolleraj@amazon.com,10,233,0,0,0,110,243,4.0,bolleraj,,,,Rajkoti Bolleddu,Paul Mathew S,US
15,budhayas@amazon.com,0,189,0,0,0,51,189,0.0,budhayas,,,,Udhaya Shankar B,Magesh D,US
16,chouanam@amazon.com,19,435,0,0,0,97,454,4.0,chouanam,,,,Anamika Chouhan,Paul Mathew S,US
17,insachin@amazon.com,6,418,0,0,0,52,424,1.0,insachin,,,,Sachin Naik,Arun Sarathy S,US
18,jawmdsaq@amazon.com,13,444,0,0,0,48,457,3.0,jawmdsaq,,,,MD SAQUIB JAWED,Anusha S,US
19,jidmat@amazon.com,4,600,1,0,0,87,604,1.0,jidmat,,,,Jidhin mathew,Saranya M L,US
20,jrahsehg@amazon.com,0,589,0,0,0,24,589,0.0,jrahsehg,,,,Rahul Sehgal,Gokul Balaiyan,US
21,krrishch@amazon.com,5,112,0,0,0,8,117,4.0,krrishch,,,,Chokkakula Krishna Murthy,Anusha S,US
22,kshlkr@amazon.com,84,618,0,0,0,124,702,12.0,kshlkr,,,,Kushal Kar,Arun Joseph,US
23,lpavkuma@amazon.com,44,212,0,0,1,9,256,17.0,lpavkuma,,,,pavan kumar,Anusha S,US
24,magukris@amazon.com,9,394,0,0,1,53,403,2.0,magukris,,,,krishna magupilli,Abhishek Prabhakar,US
25,mkupasna@amazon.com,54,921,0,0,1,26,975,6.0,mkupasna,,,,Mekala Upasna,Arun Joseph,US
26,mmt_brahma@amazon.com,0,0,0,0,0,1676,0,NaN,mmt_brahma,,,,NaN,NaN,NaN
27,mohandvi@amazon.com,9,160,0,0,0,15,169,5.0,mohandvi,,,,NaN,NaN,NaN
28,nehakj@amazon.com,0,24,0,0,0,43,24,0.0,nehakj,,,,Neha Kumari,Gokul Balaiyan,US
29,nkalyans@amazon.com,99,601,0,0,2,36,700,14.0,nkalyans,,,,Kalyan Nunnaboina,Arun Joseph,US
30,prajunan@amazon.com,1,418,0,0,0,19,419,0.0,prajunan,,,,Prajwal Nanjappa K A,Karthik S,US
31,preethko@amazon.com,92,509,1,0,1,51,601,15.0,preethko,,,,Kollabathula Preetham Satya,Arun Joseph,US
32,rashriy@amazon.com,42,555,0,0,1,15,597,7.0,rashriy,,,,Rashmi Riya,Gokul Balaiyan,US
33,renusasa@amazon.com,5,116,0,0,0,45,121,4.0,renusasa,,,,Renuka S Sasanam,Anusha S,US
34,saidsk@amazon.com,18,627,0,0,4,144,645,3.0,saidsk,,,,Desetti Saikumar,Magesh D,US
35,sanechak@amazon.com,3,532,0,0,0,15,535,1.0,sanechak,,,,Sanu Chakraborty,Anusha S,US
36,satytumm@amazon.com,95,616,0,0,2,82,711,13.0,satytumm,,,,Satya Tummala,Arun Joseph,US
37,smprashu@amazon.com,16,317,0,0,1,65,333,5.0,smprashu,,,,PRASHANTH S M,Anusha S,US
38,summaybe@amazon.com,2,186,0,0,0,6,188,1.0,summaybe,,,,Sumayya Begum,Karthik S,US
39,vaasuki@amazon.com,1,328,0,0,0,45,329,0.0,vaasuki,,,,Beerkuri Vasuki,Karthik S,US
40,vramesho@amazon.com,20,301,0,0,2,113,321,6.0,vramesho,,,,RAMESH V,Magesh D,US
41,vsandemo@amazon.com,22,280,0,0,0,20,302,7.0,vsandemo,,,,Monoswita Sandel,Abhishek Prabhaka,US

In [ ]:
final_df = final_df.rename(columns={
    "Emp Name_y": "Emp Name",
    "Manager_y": "Manager",
    "Team Name_y": "Team Name"
})
final_df = final_df.drop(
    columns=["Emp Name_x", "Manager_x", "Team Name_x"],
    errors="ignore"
)

In [ ]:
final_df["Total Audits"] = ""
final_df["Incremental IF'S"] = ""
final_df["Audited IF%"] = ""

In [ ]:
final_report = final_df[
    [
        "Emp Name",
        "user",
        "Manager",
        "Team Name",
        "Total Mappings",
        "No of IF's",
        "No of INF's",
        "IF%",
        "Total Audits",
        "Incremental IF'S",
        "Audited IF%"
    ]
]
final_report

,Emp Name,user,Manager,Team Name,Total Mappings,No of IF's,No of INF's,IF%,Total Audits,Incremental IF'S,Audited IF%
0,NaN,LLM_MISMATCH_azbmoham,NaN,NaN,4,4,0,100.0,,,
1,NaN,LLM_MISMATCH_nkalyans,NaN,NaN,1,1,0,100.0,,,
2,NaN,LLM_MISMATCH_rashriy,NaN,NaN,2,2,0,100.0,,,
3,NaN,LLM_MISMATCH_smprashu,NaN,NaN,1,1,0,100.0,,,
4,Blessing Alciya A,ablessil,Saranya M L,US,50,3,47,6.0,,,
5,NaN,afm_brew_automation,NaN,NaN,0,0,0,NaN,,,
6,AKANSHA AGGARWAL,akansagg,Karthik S,US,503,17,486,3.0,,,
7,Neeharika Akella Venkata Sai,akelneeh,Karthik S,US,510,9,501,2.0,,,
8,Shirisha Akoju,akojsiri,Arun Sarathy S,US,316,3,313,1.0,,,
9,NaN,anupriyo,NaN,NaN,237,4,233,2.0,,,
10,Arisa Rashid,arisrasp,Abhishek Prabhakar,US,353,5,348,1.0,,,
11,Arvindswamy Chandrasekaran,arvindsw,Gokul Balaiyan,US,226,35,191,15.0,,,
12,Mohammed Azarudeen,azbmoham,Saranya M L,US,432,28,404,6.0,,,
13,Hanifa,bihanifa,Arun Joseph,US,846,0,846,0.0,,,
14,Rajkoti Bolleddu,bolleraj,Paul Mathew S,US,243,10,233,4.0,,,
15,Udhaya Shankar B,budhayas,Magesh D,US,189,0,189,0.0,,,
16,Anamika Chouhan,chouanam,Paul Mathew S,US,454,19,435,4.0,,,
17,Sachin Naik,insachin,Arun Sarathy S,US,424,6,418,1.0,,,
18,MD SAQUIB JAWED,jawmdsaq,Anusha S,US,457,13,444,3.0,,,
19,Jidhin mathew,jidmat,Saranya M L,US,604,4,600,1.0,,,
20,Rahul Sehgal,jrahsehg,Gokul Balaiyan,US,589,0,589,0.0,,,
21,Chokkakula Krishna Murthy,krrishch,Anusha S,US,117,5,112,4.0,,,
22,Kushal Kar,kshlkr,Arun Joseph,US,702,84,618,12.0,,,
23,pavan kumar,lpavkuma,Anusha S,US,256,44,212,17.0,,,
24,krishna magupilli,magukris,Abhishek Prabhakar,US,403,9,394,2.0,,,
25,Mekala Upasna,mkupasna,Arun Joseph,US,975,54,921,6.0,,,
26,NaN,mmt_brahma,NaN,NaN,0,0,0,NaN,,,
27,NaN,mohandvi,NaN,NaN,169,9,160,5.0,,,
28,Neha Kumari,nehakj,Gokul Balaiyan,US,24,0,24,0.0,,,
29,Kalyan Nunnaboina,nkalyans,Arun Joseph,US,700,99,601,14.0,,,
30,Prajwal Nanjappa K A,prajunan,Karthik S,US,419,1,418,0.0,,,
31,Kollabathula Preetham Satya,preethko,Arun Joseph,US,601,92,509,15.0,,,
32,Rashmi Riya,rashriy,Gokul Balaiyan,US,597,42,555,7.0,,,
33,Renuka S Sasanam,renusasa,Anusha S,US,121,5,116,4.0,,,
34,Desetti Saikumar,saidsk,Magesh D,US,645,18,627,3.0,,,
35,Sanu Chakraborty,sanechak,Anusha S,US,535,3,532,1.0,,,
36,Satya Tummala,satytumm,Arun Joseph,US,711,95,616,13.0,,,
37,PRASHANTH S M,smprashu,Anusha S,US,333,16,317,5.0,,,
38,Sumayya Begum,summaybe,Karthik S,US,188,2,186,1.0,,,
39,Beerkuri Vasuki,vaasuki,Karthik S,US,329,1,328,0.0,,,
40,RAMESH V,vramesho,Magesh D,US,321,20,301,6.0,,,
41,Monoswita Sandel,vsandemo,Abhishek Prabhaka,US,302,22,280,7.0,,,

In [ ]:
output_path = "/content/final_report.xlsx"

final_report.to_excel(output_path, index=False)

from google.colab import files
files.download(output_path)

In [ ]:
low_eff_mappers = (
    pivot_table
    .reset_index()
    .query("IF_Percentage <= 10 & mapper_id != 'All'")
    ["mapper_id"]
    .tolist()
)
# low_eff_mappers = (
#     pivot_table
#     .reset_index()
#     .query("10 < IF_Percentage <= 20 & mapper_id != 'All'")
#     ["mapper_id"]
#     .tolist()
# )

In [ ]:
filtered_data = df[
    (df["criteria_name"].str.startswith("amzn1.goal", na=False)) &
    (df["mapper_id"].isin(low_eff_mappers)) &
    (df["mapping_status"] == "INF")
].copy()

In [ ]:
filtered_data["sku"] = (
   filtered_data["sku"]
    .astype(str)          # ensure string
    .str.zfill(10)        # pad with leading zeros
)

In [ ]:
output_path = "/content/INF_Data.xlsx"
filtered_data.to_excel(output_path, index=False)

from google.colab import files
files.download(output_path)

In [ ]:
file_path = "/content/INF_Data.xlsx"
inf_df = pd.read_excel(file_path)

inf_df.head()

,import_time_epoch,namespace,sku,competitor_name,matching_type,qualifier,source,criteria_name,location,mapping_status,...,is_mkpl_comp,afm_mode_of_comp,criteria_limit,marketplaceid,event_date,ri_matcher_tags,suggestion_reason_code,suggestion_sub_reasons,matching_type_attributes,search_tool_attributes
0,1791901988073,AMZN,B07L93N5LV,SafeWay,EXACT,NEW,ONLINE,amzn1.goal.goalService.8d6b7fa8a2082415c1c3bf7...,Any,inf,...,False,NotEnabled,0,1,2026-10-13,[],NaN,NaN,NaN,NaN
1,1791911240097,AMZN,B0GG5XDTNL,Denniskirk_MCMT,EXACT,NEW,ONLINE,amzn1.goal.goalService.ea52379b889d55d820dbe17...,Any,inf,...,False,NotEnabled,0,1,2026-10-13,[],NaN,NaN,NaN,NaN
2,1791902012343,AMZN,B01MDV3UTV,CVS,EXACT,NEW,ONLINE,amzn1.goal.goalService.8d6b7fa8a2082415c1c3bf7...,Any,inf,...,False,NotEnabled,0,1,2026-10-13,[],NaN,NaN,NaN,NaN
3,1791911257894,AMZN,B0HL91Z418,Lenovo_MCMT,EXACT,NEW,ONLINE,amzn1.goal.goalService.ea52379b889d55d820dbe17...,Any,inf,...,False,IFOnly,0,1,2026-10-13,[],NaN,NaN,NaN,NaN
4,1791865016383,AMZN,B0H6NPZZP9,Lowes,EXACT,NEW,ONLINE,amzn1.goal.goalService.9c3ac00f0f2ec209266c0a9...,Any,inf,...,False,Regular,0,1,2026-10-13,[],NaN,NaN,NaN,NaN

In [ ]:
inf_df["sku_len"] = inf_df["sku"].str.len()
inf_df["sku_len"].value_counts()

sku_len
10    11357
Name: count, dtype: int64

In [ ]:
file_path = "/content/GL_list.xlsx"
GL_list = pd.read_excel(file_path)

GL_list.head()

   gl_id              gl_code
0     14              gl_book
1     15             gl_music
2     21               gl_toy
3     23       gl_electronics
4     60  gl_home_improvement

In [ ]:
file_path = "/content/mkpl_list.xlsx"
mkpl_list = pd.read_excel(file_path)

mkpl_list.head()

  mkpl_code  client_id  marketplaceid
0        GB          9              3
1        DE         10              4
2        FR         11              5
3        US          1              1
4        CA         13              7

In [ ]:
inf_df = pd.merge(inf_df, mkpl_list[['marketplaceid', 'client_id']], on='marketplaceid', how='left')
inf_df.head()

,import_time_epoch,namespace,sku,competitor_name,matching_type,qualifier,source,criteria_name,location,mapping_status,...,criteria_limit,marketplaceid,event_date,ri_matcher_tags,suggestion_reason_code,suggestion_sub_reasons,matching_type_attributes,search_tool_attributes,sku_len,client_id
0,1791901988073,AMZN,B07L93N5LV,SafeWay,EXACT,NEW,ONLINE,amzn1.goal.goalService.8d6b7fa8a2082415c1c3bf7...,Any,inf,...,0,1,2026-10-13,[],NaN,NaN,NaN,NaN,10,1
1,1791911240097,AMZN,B0GG5XDTNL,Denniskirk_MCMT,EXACT,NEW,ONLINE,amzn1.goal.goalService.ea52379b889d55d820dbe17...,Any,inf,...,0,1,2026-10-13,[],NaN,NaN,NaN,NaN,10,1
2,1791902012343,AMZN,B01MDV3UTV,CVS,EXACT,NEW,ONLINE,amzn1.goal.goalService.8d6b7fa8a2082415c1c3bf7...,Any,inf,...,0,1,2026-10-13,[],NaN,NaN,NaN,NaN,10,1
3,1791911257894,AMZN,B0HL91Z418,Lenovo_MCMT,EXACT,NEW,ONLINE,amzn1.goal.goalService.ea52379b889d55d820dbe17...,Any,inf,...,0,1,2026-10-13,[],NaN,NaN,NaN,NaN,10,1
4,1791865016383,AMZN,B0H6NPZZP9,Lowes,EXACT,NEW,ONLINE,amzn1.goal.goalService.9c3ac00f0f2ec209266c0a9...,Any,inf,...,0,1,2026-10-13,[],NaN,NaN,NaN,NaN,10,1

In [ ]:
inf_df.shape

(11357, 37)

In [ ]:
gl_map = (
    GL_list
    .drop_duplicates("gl_code")   # lookup table only
    .set_index("gl_code")["gl_id"]
)

inf_df["gl_id"] = inf_df["gl_code"].map(gl_map)

In [ ]:
inf_df.shape

(11357, 38)

In [ ]:
output_df = pd.DataFrame({
    "Namespace": "AMZN",
    "Sku": inf_df["sku"],
    "mapper_id": inf_df["mapper_id"],
    "Qualifier": "NEW",
    "CompId": inf_df["competitor_name"],
    "MarketplaceId": inf_df["marketplaceid"],
    "MatchingType": "EXACT",
    "Location": "",
    "Source": "ONLINE",
    "Tag": "BM_INF_AuditML_1410_US",
    "clientId": inf_df["client_id"],
    "compSearchUrl": "",
    "gl_code": inf_df["gl_code"],
    "gvBand": inf_df["band"],
    "gl_id": inf_df["gl_id"]
})

In [ ]:
import numpy as np

# fixed seed ensures reproducibility
np.random.seed(42)

output_df["rand"] = np.random.rand(len(inf_df))

output_df = output_df.sort_values(["mapper_id", "rand"])

output_df["group_rank"] = (
    output_df
    .groupby("mapper_id")
    .cumcount() + 1
)

In [ ]:
output_df.columns

Index(['Namespace', 'Sku', 'mapper_id', 'Qualifier', 'CompId', 'MarketplaceId',
       'MatchingType', 'Location', 'Source', 'Tag', 'clientId',
       'compSearchUrl', 'gl_code', 'gvBand', 'gl_id', 'rand', 'group_rank'],
      dtype='object')

In [ ]:
pivot_mapper_count = (
    output_df
    .pivot_table(
        index="mapper_id",
        values="Sku",   # or any non-null column
        aggfunc="count"
    )
    .reset_index()
    .rename(columns={"Sku": "mapper_count"})
)
pivot_mapper_count

              mapper_id  mapper_count
0   ablessil@amazon.com            47
1   akansagg@amazon.com           486
2   akelneeh@amazon.com           501
3   akojsiri@amazon.com           313
4   anupriyo@amazon.com           233
5   arisrasp@amazon.com           348
6   azbmoham@amazon.com           404
7   bihanifa@amazon.com           846
8   bolleraj@amazon.com           233
9   budhayas@amazon.com           189
10  chouanam@amazon.com           435
11  insachin@amazon.com           418
12  jawmdsaq@amazon.com           444
13    jidmat@amazon.com           600
14  jrahsehg@amazon.com           589
15  krrishch@amazon.com           112
16  magukris@amazon.com           394
17  mkupasna@amazon.com           921
18  mohandvi@amazon.com           160
19    nehakj@amazon.com            24
20  prajunan@amazon.com           418
21   rashriy@amazon.com           555
22  renusasa@amazon.com           116
23    saidsk@amazon.com           627
24  sanechak@amazon.com           532
25  smprashu@amazon.com           317
26  summaybe@amazon.com           186
27   vaasuki@amazon.com           328
28  vramesho@amazon.com           301
29  vsandemo@amazon.com           280

In [ ]:
import pandas as pd

audit_dfs = []
audit_counts = []

for _, row in pivot_mapper_count.iterrows():
    mapper = row["mapper_id"]
    max_count = row["mapper_count"]

    while True:
        try:
            user_count = int(
                input(f"Enter audit count for {mapper} (max {max_count}): ")
            )
            if 0 <= user_count <= max_count:
                break
            else:
                print(f"❌ Enter a value between 0 and {max_count}")
        except ValueError:
            print("❌ Please enter a valid integer")

    # store entered count
    audit_counts.append({
        "mapper_id": mapper,
        "total_INF": max_count,
        "audit_count_entered": user_count
    })

    filtered_df = output_df[
        (output_df["mapper_id"] == mapper) &
        (output_df["group_rank"] <= user_count)
    ]

    audit_dfs.append(filtered_df)

Enter audit count for ablessil@amazon.com (max 47): 6
Enter audit count for akansagg@amazon.com (max 486): 57
Enter audit count for akelneeh@amazon.com (max 501): 58
Enter audit count for akojsiri@amazon.com (max 313): 37
Enter audit count for anupriyo@amazon.com (max 233): 27
Enter audit count for arisrasp@amazon.com (max 348): 41
Enter audit count for azbmoham@amazon.com (max 404): 48
Enter audit count for bihanifa@amazon.com (max 846): 100
Enter audit count for bolleraj@amazon.com (max 233): 27
Enter audit count for budhayas@amazon.com (max 189): 22
Enter audit count for chouanam@amazon.com (max 435): 51
Enter audit count for insachin@amazon.com (max 418): 49
Enter audit count for jawmdsaq@amazon.com (max 444): 52
Enter audit count for jidmat@amazon.com (max 600): 71
Enter audit count for jrahsehg@amazon.com (max 589): 69
Enter audit count for krrishch@amazon.com (max 112): 13
Enter audit count for magukris@amazon.com (max 394): 46
Enter audit count for mkupasna@amazon.com (max 921): 108
Enter audit count for mohandvi@amazon.com (max 160): 19
Enter audit count for nehakj@amazon.com (max 24): 3
Enter audit count for prajunan@amazon.com (max 418): 49
Enter audit count for rashriy@amazon.com (max 555): 65
Enter audit count for renusasa@amazon.com (max 116): 14
Enter audit count for saidsk@amazon.com (max 627): 74
Enter audit count for sanechak@amazon.com (max 532): 63
Enter audit count for smprashu@amazon.com (max 317): 37
Enter audit count for summaybe@amazon.com (max 186): 22
Enter audit count for vaasuki@amazon.com (max 328): 39
Enter audit count for vramesho@amazon.com (max 301): 35
Enter audit count for vsandemo@amazon.com (max 280): 33

In [ ]:
final_audit_df = pd.concat(audit_dfs, ignore_index=True)
audit_count_df = pd.DataFrame(audit_counts)

In [ ]:
final_audit_df.mapper_id.unique()

array(['ablessil@amazon.com', 'akansagg@amazon.com',
       'akelneeh@amazon.com', 'akojsiri@amazon.com',
       'anupriyo@amazon.com', 'arisrasp@amazon.com',
       'azbmoham@amazon.com', 'bihanifa@amazon.com',
       'bolleraj@amazon.com', 'budhayas@amazon.com',
       'chouanam@amazon.com', 'insachin@amazon.com',
       'jawmdsaq@amazon.com', 'jidmat@amazon.com', 'jrahsehg@amazon.com',
       'krrishch@amazon.com', 'magukris@amazon.com',
       'mkupasna@amazon.com', 'mohandvi@amazon.com', 'nehakj@amazon.com',
       'prajunan@amazon.com', 'rashriy@amazon.com', 'renusasa@amazon.com',
       'saidsk@amazon.com', 'sanechak@amazon.com', 'smprashu@amazon.com',
       'summaybe@amazon.com', 'vaasuki@amazon.com', 'vramesho@amazon.com',
       'vsandemo@amazon.com'], dtype=object)

In [ ]:
final_audit_df = final_audit_df.drop(columns=["rand", "group_rank", "gl_code"])

In [ ]:
final_audit_df = final_audit_df.rename(columns={"gl_id": "gl"})

In [ ]:
desired_columns = [
    'Namespace', 'Sku', 'mapper_id', 'Qualifier', 'CompId', 'MarketplaceId',
    'MatchingType', 'Location', 'Source', 'Tag', 'clientId',
    'compSearchUrl', 'gl', 'gvBand'
]

final_audit_df = final_audit_df[desired_columns]

In [ ]:
final_audit_df.columns

Index(['Namespace', 'Sku', 'mapper_id', 'Qualifier', 'CompId', 'MarketplaceId',
       'MatchingType', 'Location', 'Source', 'Tag', 'clientId',
       'compSearchUrl', 'gl', 'gvBand'],
      dtype='object')

In [ ]:
final_audit_df.head()

,Namespace,Sku,mapper_id,Qualifier,CompId,MarketplaceId,MatchingType,Location,Source,Tag,clientId,compSearchUrl,gl,gvBand
0,AMZN,B0FD1TB55X,ablessil@amazon.com,NEW,Lowes,1,EXACT,,ONLINE,BM_INF_AuditML_1410_US,1,,469,D
1,AMZN,B0892T6JV2,ablessil@amazon.com,NEW,Lowes,1,EXACT,,ONLINE,BM_INF_AuditML_1410_US,1,,201,E
2,AMZN,B00002N6FF,ablessil@amazon.com,NEW,AcmeTools,1,EXACT,,ONLINE,BM_INF_AuditML_1410_US,1,,60,NaN
3,AMZN,B07F1KB74T,ablessil@amazon.com,NEW,BedBathBeyond,1,EXACT,,ONLINE,BM_INF_AuditML_1410_US,1,,201,C
4,AMZN,B0DB8WLRVL,ablessil@amazon.com,NEW,Belk,1,EXACT,,ONLINE,BM_INF_AuditML_1410_US,1,,79,D

In [ ]:
output_path = "/content/tag_file.xlsx"
final_audit_df.to_excel(output_path, index=False)

from google.colab import files
files.download(output_path)

In [ ]:
file_path = "/content/tag_file.xlsx"
tag_file = pd.read_excel(file_path)

tag_file.head()

,Namespace,Sku,mapper_id,Qualifier,CompId,MarketplaceId,MatchingType,Location,Source,Tag,clientId,compSearchUrl,gl,gvBand
0,AMZN,B0FD1TB55X,ablessil@amazon.com,NEW,Lowes,1,EXACT,NaN,ONLINE,BM_INF_AuditML_1410_US,1,NaN,469,D
1,AMZN,B0892T6JV2,ablessil@amazon.com,NEW,Lowes,1,EXACT,NaN,ONLINE,BM_INF_AuditML_1410_US,1,NaN,201,E
2,AMZN,B00002N6FF,ablessil@amazon.com,NEW,AcmeTools,1,EXACT,NaN,ONLINE,BM_INF_AuditML_1410_US,1,NaN,60,NaN
3,AMZN,B07F1KB74T,ablessil@amazon.com,NEW,BedBathBeyond,1,EXACT,NaN,ONLINE,BM_INF_AuditML_1410_US,1,NaN,201,C
4,AMZN,B0DB8WLRVL,ablessil@amazon.com,NEW,Belk,1,EXACT,NaN,ONLINE,BM_INF_AuditML_1410_US,1,NaN,79,D